# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
name: Autograding
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-18.04
    container: rocker/geospatial:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
          install.packages(c("testthat","tidyverse","RCurl","questionr"))
        shell: Rscript {0}
      - name: Install all needed packages
        run: questionr::qscan(list.files(pattern="*.R",recursive=T), load = TRUE, detail = FALSE)
        shell: Rscript {0}
  CS01:
    needs: setup
    - name: Case Study 01
      run: testthat::test_file("tests/testthat/test-CS01.R",stop_on_failure = FALSE,reporter = "progress")
      shell: Rscript {0}
  CS02:
    needs: setup
    - name: Case Study 02
      run: testthat::test_file("tests/testthat/test-CS02.R",stop_on_failure = FALSE,reporter = "progress")
      shell: Rscript {0}
      
