# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
name: classroom-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    container: rocker/geospatial:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
          install.packages(c("testthat","tidyverse","RCurl"))
        shell: Rscript {0}
      - name: Run Testthat
        run: source("tests/testthat.R")
        shell: Rscript {0}

      
      